spring:
  application:
    name: Management_System
  datasource:
      url: jdbc:mysql://localhost:3306/ms
      username: root
      password: 71304002yll
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    map-underscore-to-camel-case: true